version: '3.8'

services:
  postgres:
    image: 'postgres:13.2'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
      POSTGRES_PORT: 5432
